runtime: python311
entrypoint: gunicorn -b :$PORT api_server:app

env_variables:
  GOOGLE_API_KEY: "AIzaSyBLtja16fqBY1EmkA3WQ2gT9hpJZD9xJIQ"
  
# Optional: Auto-Scaling Settings (Standard defaults are usually fine)
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
